name = "duindocs"
main = ".open-next/worker.js"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]

compatibility_flags = [
    # Enable Node.js API
    # see https://developers.cloudflare.com/workers/configuration/compatibility-flags/#nodejs-compatibility-flag
    "nodejs_compat",
    # Allow to fetch URLs in your app
    # see https://developers.cloudflare.com/workers/configuration/compatibility-flags/#global-fetch-strictly-public
    "global_fetch_strictly_public"
]

[assets]
directory = ".open-next/assets"
binding   = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
# The service should match the "name" of your worker
service = "duindocs"

